---
title: "Welcome to Song's blog"
date: 2021-05-19
---

title: Welcome to Song's blog
author: Song Gao
email: 657259920@qq.com
description: > # this means to ignore newlines until "baseurl:"
  A new one to the real world! 
  The road ahead will be long and our climb will be steep.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
